baseURL = 'https://michygit.github.io/github.io/'
locale = 'ja-ja'
title = 'みっちゃんサイト'

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[Params]
  subtitle = "みっちゃんつぶやき"
  mainSections = ["post", "posts"]
#  logo = "/img/avatar-icon.png"
  favicon = "/img/favicon.ico"
  dateFormat = "2006-01-02"
  colorScheme = "dark"
  readingTime = false
  socialShare = false
  showRelatedPosts = true
  rss = false
  headerImgStyle = "narrow"
  bigimg = [{src = "img/dio2-checker.png", desc = "", position = "center"}]

[Params.search]
    provider = 'fuse'

[Params.author]
  name = "Michinori Ichikawa"
#  website = "https://michygit.github.io/github.io/"
  email = "michy@gray.plala.or.jp"
#  github = "michygit"

[markup.highlight]
  noClasses = false

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true
  
[markup.goldmark.renderHooks.image]
  useEmbedded = "always"
[[module.mounts]]
  source = 'assets'
  target = 'assets'
[[module.mounts]]
  source = 'static'
  target = 'assets'
